name: wanna_bet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  # firebase_auth: ^5.4.2
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pokerChip1.png
    - assets/pokerChip2.png
    - assets/animation1.json
    - assets/animation1.gif
    - assets/animation2.json
    - assets/animation3.json
    - assets/signUpAnimation.json
