name: wannabet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  cloud_firestore: ^5.6.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/pokerChip1.png
    - assets/pokerChip2.png
    - assets/animation1.json
    - assets/animation1.gif
    - assets/animation2.json
    - assets/animation3.json
    - assets/signUpAnimation.json
    - assets/logInAnimation.json
    - assets/noSearchResultsAnimation.json
    - assets/noNotificationsAnimation.json
    - assets/friendRequestSentAnimation.json
    - assets/noFriendsAnimation.json
    - assets/acceptFriendRequestHeartAnimation.json
    - assets/denyFriendRequestXAnimation.json
    - assets/betSentAnimation.json
    - assets/noBetInvitesAnimation.json
    - assets/acceptBetInviteAnimation.json
    - assets/denyBetInviteAnimation.json
    - assets/noFriendsAnimation2.json