// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYaal4fi4RcCqYlwBoj7jI9OZHXIEwqsQ',
    appId: '1:237774613003:web:ecdd343c9c9f45a03e750e',
    messagingSenderId: '237774613003',
    projectId: 'wannabet-30ac9',
    authDomain: 'wannabet-30ac9.firebaseapp.com',
    storageBucket: 'wannabet-30ac9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8MBxzoxkJ_41GOX1CRa_D_-w8xtewHXM',
    appId: '1:237774613003:android:82262526de5afe573e750e',
    messagingSenderId: '237774613003',
    projectId: 'wannabet-30ac9',
    storageBucket: 'wannabet-30ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYACOZIm3QtL9VLRwqsF9P4UdBW3Lc1ss',
    appId: '1:237774613003:ios:9c78afaf0a717f923e750e',
    messagingSenderId: '237774613003',
    projectId: 'wannabet-30ac9',
    storageBucket: 'wannabet-30ac9.firebasestorage.app',
    iosBundleId: 'com.example.wannaBet',
  );
}
